### ISSUE TITLE
A customer can contact admin

### ISSUE THREAD

**Issue by Yogesh-34** [Comp231-S4G2/PharmaGoProject#19]
#21 Classes and methods for contact admin page
#30 UI of contact admin page

Note: Will we require a reason why on delete account request?
Note for UI: Drop down menu, Text field for topic, Text field for feedback, submit button

Test will all required fields filled out 
Test without topic field filled out 
Test without tech support info field filled out 
Test submit button 
Test receiving request by Admin

**Comment by HarmanPannu19** [comment]
Merge pull request complete the user storey
